language: node_js
node_js: "4.1"
before_install:
  - sudo apt-get install imagemagick -y
  - sudo add-apt-repository ppa:dhor/myway -y
  - sudo apt-get update -y
  - sudo apt-get install graphicsmagick -y
install:
  - npm install
  - npm install -g gulp
  - npm install -g casperjs
before_script:
  - gulp build --cwd=bookmarklet
  - gulp server --cwd=bookmarklet &
  - sleep 3 # give the server a head start
script: npm test